---
title: "covid-immigrant-foodworkers"
author: "Joe Yerardi"
date: "5/7/2020"
output: html_document
---

```{r setup, include = F}
# We want to hide the code and only see the results
knitr::opts_chunk$set(echo = F)

# We don't want to see any warnings from our code
knitr::opts_chunk$set(warning = F)

# We don't want to see any messages
knitr::opts_chunk$set(message = F)

# Set key file for the Census Bureau API key
key_file <- "key_file.txt"
```

```{r, include = F}
library(ipumsr)
library(labelled)
library(purrr)
library(rgdal)
library(sf)
library(tidycensus)
library(tidyverse)
library(tigris)
```

```{r import and format data}
# IPUMS (2014-18 ACS; population = 16 and older; employed - at work, employed - not at work)
ipums <- read.table("data/usa_00015.dat")
ddi <- read_ipums_ddi("data/usa_00015.xml")
ipums <- read_ipums_micro(ddi) %>% 
  mutate(state_code = as_factor(US2018C_ST, levels = "values"),
         state = as_factor(US2018C_ST, levels = "labels"),
         puma_code = paste0(state_code, as_factor(US2018C_PUMA)),
         industry_code = as_factor(US2018C_INDP, levels = "values"),
         industry = as_factor(US2018C_INDP, levels = "labels"),
         occupation_code =  as_factor(US2018C_OCCP, levels = "values"),
         occupation = as_factor(US2018C_OCCP, levels = "labels"),
         citizenship_code = as_factor(CITIZEN, levels = "values"),
         citizenship = as_factor(CITIZEN, levels = "labels"),
         ethnicity_code = as_factor(HISPAN, levels = "values"),
         ethnicity = as_factor(HISPAN, levels = "labels")) %>% 
  select(16:26, 5)

# PUMA shapefiles
pumas <- readOGR("data/ipums_puma_2010/ipums_puma_2010.shp") %>% 
  # Convert shapefile to sf object
  st_as_sf(crs = 5070, remove = F) %>% 
  select(puma_code = GEOID, puma = Name, geometry)

# County shapefiles
counties <- readOGR("data/tl_2019_us_county/tl_2019_us_county.shp") %>% 
  # Convert shapefile to sf object
  st_as_sf(crs = 5070, remove = F) %>% 
  select(county_code = GEOID, county = NAMELSAD, geometry)

# COVID county cases and deaths
covid <- read_csv("data/us-counties.csv",
                  col_types = cols(.default = "?", date = "D")) %>% 
  rename(county_code = fips) %>% 
  # Filter to the latest data for each county
  group_by(county_code) %>% 
  slice(which.max(date))

# County populations
# Read-in Census API key
census_key <- (readLines(key_file)[1])

# Create list of all US states to iterate through in the API calls
us <- unique(fips_codes$state)[1:51]

# Download population data from the 2014-2018 ACS
population <- map_df(us, function(x) {
  get_acs(geography = "county", variables = "B01001_001", 
          state = x, key = census_key)
}) %>% 
  mutate(income_quartile = ntile(estimate, 4)) %>% 
  select(county_code = GEOID,
         county = NAME,
         population = estimate)

# PUMA-to-county crosswalk
crosswalk <- read_csv("data/geocorr2018.csv", skip = 1) %>% 
  mutate(puma_code = paste0(`State code`, `PUMA (2012)`)) %>% 
  select(puma_code,
         county_code = `County code (2014)`,
         state = `State abbreviation`,
         county = `2014 county name`,
         puma = `PUMA12 name`,
         allocation_factor = `puma12 to county14 allocation factor`)
```

```{r join the covid, population and crosswalk data frames}
# Join the covid, population and crosswalk data frames
crosswalk <- list(covid, population, crosswalk) %>% 
  reduce(full_join, by = "county_code") %>% 
  mutate(puma = paste(puma, state.x, sep = ", "),
         cases_per_100k = round(cases / population * 100000, digits = 0),
         deaths_per_100k = round(deaths / population * 100000, digits = 0)) %>% 
  select(1,
         state = state.x,
         county_code,
         county = county.y,
         puma_code,
         puma,
         population,
         cases,
         deaths,
         cases_per_100k,
         deaths_per_100k,
         allocation_factor)
```

```{r filter the industries}
# Filter to the food production industries we're interested in.
# Crop production; Animal production and aquaculture; Support activities for agriculture and forestry; Animal food; grain and oilseed milling; Sugar and confectionery products; Fruit and vegetable preserving and specialty food manufacturing; Dairy product manufacturing; Animal slaughtering and processing; Bakeries and tortilla manufacturing; except retail bakeries; Seafood and other miscellaneous foods; n.e.c.; Not specified food industries
food_production_industries <- list("0170", "0180", "0290", "1070", "1080", "1090", "1170", "1180", "1270", "1280", "1290")

ipums_food_production <- ipums %>% 
  filter(industry_code %in% food_production_industries)
```

```{r calculate employment by industry-occupation groupings and filter}
# Calculate employment by industry-occupation grouping
ipums_food_production_total_employment_by_ind_occ <- ipums_food_production %>% 
  group_by(industry, occupation) %>% 
  summarize(num_employees = sum(PERWT)) %>% 
  pivot_wider(id_cols = c(industry, occupation),
              values_from = num_employees,
              names_prefix = "num_employees") %>% 
  replace(is.na(.), 0) %>% 
# Exclude from our analysis ind-occ groupings with fewer than 2,500 employees nationally
  filter(num_employees >= 2500)

# Export the data
write_csv(ipums_food_production_total_employment_by_ind_occ, "data/exported/ipums_food_production_total_employment_by_ind_occ.csv")
```

```{r filter the industry-occupation pairs}
# Import data frame of food production industry-occupation pairs
ipums_food_production_total_employment_by_ind_occ <- read_csv("data/ipums_food_production_total_employment_by_ind_occ.csv")

# Join the industry-occupation pairs to the ipums data and filter to just the industry-occupation pairs we want
ipums_food_production_selected_occupations <- ipums_food_production %>% 
  inner_join(ipums_food_production_total_employment_by_ind_occ, by = c("industry", "occupation")) %>% 
  filter(exclude == FALSE) %>% 
  select(-num_employees,
         -exclude)

# And join with the pumas data frame to get the PUMA names
ipums_food_production_selected_occupations <- ipums_food_production_selected_occupations %>% 
  left_join(pumas, by = "puma_code") %>% 
  mutate(puma = paste(puma, state, sep = ", ")) %>% 
  select(1:3,
         13,
         4:12)
```

```{r calculate the national-level citizenship and ethnicity data for these industry-occupation pairs}
ipums_food_production_by_industry_occupation <- ipums_food_production_selected_occupations %>% 
  group_by(industry_code, industry, occupation_code, occupation, citizenship_code, ethnicity_code) %>% 
  summarize(num_employees = sum(PERWT)) %>% 
  pivot_wider(id_cols = c(industry_code, industry, occupation_code, occupation),
              names_from = c(citizenship_code, ethnicity_code),
              values_from = num_employees,
              names_prefix = "col_") %>% 
  replace(is.na(.), 0) %>% 
  mutate(native_citizen_non_hispanic = col_0_0 + col_1_0,
         native_citizen_hispanic = col_0_1 + col_0_2 + col_0_3 + col_0_4 + col_1_1 + col_1_2 + col_1_3 + col_1_4,
         total_foreign_non_hispanic = col_2_0 + col_3_0,
         total_foreign_hispanic = col_2_1 + col_2_2 + col_2_3 + col_2_4 + col_3_1 + col_3_2 + col_3_3 + col_3_4,
         naturalized_citizen_non_hispanic = col_2_0,
         naturalized_citizen_hispanic = col_2_1 + col_2_2 + col_2_3 + col_2_4,
         non_citizen_non_hispanic = col_3_0,
         non_citizen_hispanic = col_3_1 + col_3_2 + col_3_3 + col_3_4,
         total_employees = native_citizen_non_hispanic + native_citizen_hispanic + total_foreign_non_hispanic + total_foreign_hispanic,
         pct_native_citizen_non_hispanic = round(native_citizen_non_hispanic / total_employees * 100, digits = 0),
         pct_native_citizen_hispanic = round(native_citizen_hispanic / total_employees * 100, digits = 0),
         pct_total_foreign_non_hispanic = round(total_foreign_non_hispanic / total_employees * 100, digits = 0),
         pct_total_foreign_hispanic = round(total_foreign_hispanic / total_employees * 100, digits = 0),
         pct_naturalized_citizen_non_hispanic = round(naturalized_citizen_non_hispanic / total_employees * 100, digits = 0),
         pct_naturalized_citizen_hispanic = round(naturalized_citizen_hispanic / total_employees * 100, digits = 0),
         pct_non_citizen_non_hispanic = round(non_citizen_non_hispanic / total_employees * 100, digits = 0),
         pct_non_citizen_hispanic = round(non_citizen_hispanic / total_employees * 100, digits = 0),
         native_citizen = native_citizen_non_hispanic + native_citizen_hispanic,
         total_foreign = total_foreign_non_hispanic + total_foreign_hispanic,
         naturalized_citizen = naturalized_citizen_non_hispanic + naturalized_citizen_hispanic,
         non_citizen = non_citizen_non_hispanic + non_citizen_hispanic,
         pct_native_citizen = round(native_citizen / total_employees * 100, digits = 0),
         pct_total_foreign = round(total_foreign / total_employees * 100, digits = 0),
         pct_naturalized_citizen = round(naturalized_citizen / total_employees * 100, digits = 0),
         pct_non_citizen = round(non_citizen / total_employees * 100, digits = 0),
         total_employment = native_citizen_non_hispanic + native_citizen_hispanic + total_foreign_non_hispanic + total_foreign_hispanic) %>% 
  select(industry_code,
         industry,
         occupation_code,
         occupation,
         total_employment,
         native_citizen,
         native_citizen_non_hispanic,
         native_citizen_hispanic,
         total_foreign,
         total_foreign_non_hispanic,
         total_foreign_hispanic,
         naturalized_citizen,
         naturalized_citizen_non_hispanic,
         naturalized_citizen_hispanic,
         non_citizen,
         non_citizen_non_hispanic,
         non_citizen_hispanic,
         pct_native_citizen,
         pct_native_citizen_non_hispanic,
         pct_native_citizen_hispanic,
         pct_total_foreign,
         pct_total_foreign_non_hispanic,
         pct_total_foreign_hispanic,
         pct_naturalized_citizen,
         pct_naturalized_citizen_non_hispanic,
         pct_naturalized_citizen_hispanic,
         pct_non_citizen,
         pct_non_citizen_non_hispanic,
         pct_non_citizen_hispanic)

# Export the data
write_csv(ipums_food_production_by_industry_occupation, "data/exported/ipums_food_production_by_industry_occupation.csv")
```

```{r group the data by PUMA}
ipums_food_production_by_puma <- ipums_food_production_selected_occupations %>% 
  group_by(state_code, state, puma_code, puma, citizenship_code, ethnicity_code) %>% 
  summarize(num_employees = sum(PERWT)) %>% 
  pivot_wider(id_cols = c(state_code, state, puma_code, puma),
              names_from = c(citizenship_code, ethnicity_code),
              values_from = num_employees,
              names_prefix = "col_") %>% 
  replace(is.na(.), 0) %>% 
  mutate(native_citizen_non_hispanic = col_0_0 + col_1_0,
         native_citizen_hispanic = col_0_1 + col_0_2 + col_0_3 + col_0_4 + col_1_1 + col_1_2 + col_1_3 + col_1_4,
         total_foreign_non_hispanic = col_2_0 + col_3_0,
         total_foreign_hispanic = col_2_1 + col_2_2 + col_2_3 + col_2_4 + col_3_1 + col_3_2 + col_3_3 + col_3_4,
         naturalized_citizen_non_hispanic = col_2_0,
         naturalized_citizen_hispanic = col_2_1 + col_2_2 + col_2_3 + col_2_4,
         non_citizen_non_hispanic = col_3_0,
         non_citizen_hispanic = col_3_1 + col_3_2 + col_3_3 + col_3_4,
         total_employees = native_citizen_non_hispanic + native_citizen_hispanic + total_foreign_non_hispanic + total_foreign_hispanic,
         pct_native_citizen_non_hispanic = round(native_citizen_non_hispanic / total_employees * 100, digits = 0),
         pct_native_citizen_hispanic = round(native_citizen_hispanic / total_employees * 100, digits = 0),
         pct_total_foreign_non_hispanic = round(total_foreign_non_hispanic / total_employees * 100, digits = 0),
         pct_total_foreign_hispanic = round(total_foreign_hispanic / total_employees * 100, digits = 0),
         pct_naturalized_citizen_non_hispanic = round(naturalized_citizen_non_hispanic / total_employees * 100, digits = 0),
         pct_naturalized_citizen_hispanic = round(naturalized_citizen_hispanic / total_employees * 100, digits = 0),
         pct_non_citizen_non_hispanic = round(non_citizen_non_hispanic / total_employees * 100, digits = 0),
         pct_non_citizen_hispanic = round(non_citizen_hispanic / total_employees * 100, digits = 0),
         native_citizen = native_citizen_non_hispanic + native_citizen_hispanic,
         total_foreign = total_foreign_non_hispanic + total_foreign_hispanic,
         naturalized_citizen = naturalized_citizen_non_hispanic + naturalized_citizen_hispanic,
         non_citizen = non_citizen_non_hispanic + non_citizen_hispanic,
         pct_native_citizen = round(native_citizen / total_employees * 100, digits = 0),
         pct_total_foreign = round(total_foreign / total_employees * 100, digits = 0),
         pct_naturalized_citizen = round(naturalized_citizen / total_employees * 100, digits = 0),
         pct_non_citizen = round(non_citizen / total_employees * 100, digits = 0),
         total_employment_selected_industries = native_citizen_non_hispanic + native_citizen_hispanic + total_foreign_non_hispanic + total_foreign_hispanic) %>% 
  select(state_code,
         state,
         puma_code,
         puma,
         total_employment_selected_industries,
         native_citizen,
         native_citizen_non_hispanic,
         native_citizen_hispanic,
         total_foreign,
         total_foreign_non_hispanic,
         total_foreign_hispanic,
         naturalized_citizen,
         naturalized_citizen_non_hispanic,
         naturalized_citizen_hispanic,
         non_citizen,
         non_citizen_non_hispanic,
         non_citizen_hispanic,
         pct_native_citizen,
         pct_native_citizen_non_hispanic,
         pct_native_citizen_hispanic,
         pct_total_foreign,
         pct_total_foreign_non_hispanic,
         pct_total_foreign_hispanic,
         pct_naturalized_citizen,
         pct_naturalized_citizen_non_hispanic,
         pct_naturalized_citizen_hispanic,
         pct_non_citizen,
         pct_non_citizen_non_hispanic,
         pct_non_citizen_hispanic)

# Export the data
write_csv(ipums_food_production_by_puma, "data/exported/ipums_food_production_by_puma.csv")
```

```{r group the data by PUMA and industry and occupation}
ipums_food_production_by_puma_ind_occ <- ipums_food_production_selected_occupations %>% 
  group_by(state_code, state, puma_code, puma, industry_code, industry, occupation_code, occupation, citizenship_code, ethnicity_code) %>% 
  summarize(num_employees = sum(PERWT)) %>% 
  pivot_wider(id_cols = c(state_code, state, puma_code, puma, industry_code, industry, occupation_code, occupation),
              names_from = c(citizenship_code, ethnicity_code),
              values_from = num_employees,
              names_prefix = "col_") %>% 
  replace(is.na(.), 0) %>% 
  mutate(native_citizen_non_hispanic = col_0_0 + col_1_0,
         native_citizen_hispanic = col_0_1 + col_0_2 + col_0_3 + col_0_4 + col_1_1 + col_1_2 + col_1_3 + col_1_4,
         total_foreign_non_hispanic = col_2_0 + col_3_0,
         total_foreign_hispanic = col_2_1 + col_2_2 + col_2_3 + col_2_4 + col_3_1 + col_3_2 + col_3_3 + col_3_4,
         naturalized_citizen_non_hispanic = col_2_0,
         naturalized_citizen_hispanic = col_2_1 + col_2_2 + col_2_3 + col_2_4,
         non_citizen_non_hispanic = col_3_0,
         non_citizen_hispanic = col_3_1 + col_3_2 + col_3_3 + col_3_4,
         total_employees = native_citizen_non_hispanic + native_citizen_hispanic + total_foreign_non_hispanic + total_foreign_hispanic,
         pct_native_citizen_non_hispanic = round(native_citizen_non_hispanic / total_employees * 100, digits = 0),
         pct_native_citizen_hispanic = round(native_citizen_hispanic / total_employees * 100, digits = 0),
         pct_total_foreign_non_hispanic = round(total_foreign_non_hispanic / total_employees * 100, digits = 0),
         pct_total_foreign_hispanic = round(total_foreign_hispanic / total_employees * 100, digits = 0),
         pct_naturalized_citizen_non_hispanic = round(naturalized_citizen_non_hispanic / total_employees * 100, digits = 0),
         pct_naturalized_citizen_hispanic = round(naturalized_citizen_hispanic / total_employees * 100, digits = 0),
         pct_non_citizen_non_hispanic = round(non_citizen_non_hispanic / total_employees * 100, digits = 0),
         pct_non_citizen_hispanic = round(non_citizen_hispanic / total_employees * 100, digits = 0),
         native_citizen = native_citizen_non_hispanic + native_citizen_hispanic,
         total_foreign = total_foreign_non_hispanic + total_foreign_hispanic,
         naturalized_citizen = naturalized_citizen_non_hispanic + naturalized_citizen_hispanic,
         non_citizen = non_citizen_non_hispanic + non_citizen_hispanic,
         pct_native_citizen = round(native_citizen / total_employees * 100, digits = 0),
         pct_total_foreign = round(total_foreign / total_employees * 100, digits = 0),
         pct_naturalized_citizen = round(naturalized_citizen / total_employees * 100, digits = 0),
         pct_non_citizen = round(non_citizen / total_employees * 100, digits = 0),
         total_employment_selected_industries = native_citizen_non_hispanic + native_citizen_hispanic + total_foreign_non_hispanic + total_foreign_hispanic) %>% 
  select(state_code,
         state,
         puma_code,
         puma,
         industry_code,
         industry,
         occupation_code,
         occupation,
         total_employment_selected_industries,
         native_citizen,
         native_citizen_non_hispanic,
         native_citizen_hispanic,
         total_foreign,
         total_foreign_non_hispanic,
         total_foreign_hispanic,
         naturalized_citizen,
         naturalized_citizen_non_hispanic,
         naturalized_citizen_hispanic,
         non_citizen,
         non_citizen_non_hispanic,
         non_citizen_hispanic,
         pct_native_citizen,
         pct_native_citizen_non_hispanic,
         pct_native_citizen_hispanic,
         pct_total_foreign,
         pct_total_foreign_non_hispanic,
         pct_total_foreign_hispanic,
         pct_naturalized_citizen,
         pct_naturalized_citizen_non_hispanic,
         pct_naturalized_citizen_hispanic,
         pct_non_citizen,
         pct_non_citizen_non_hispanic,
         pct_non_citizen_hispanic)

# Export the data
write_csv(ipums_food_production_by_puma_ind_occ, "data/exported/ipums_food_production_by_puma_ind_occ.csv")
```

```{r crosswalk the employment data from PUMAs to counties}
# Join the employment data to the crosswalk data frame
ipums_food_production_by_puma_crosswalked_to_county <- ipums_food_production_by_puma %>% 
  left_join(crosswalk, by = "puma_code") %>% 
  mutate(total_employment_selected_industries = round(total_employment_selected_industries * allocation_factor, digits = 0),
         native_citizen_non_hispanic = round(native_citizen_non_hispanic * allocation_factor, digits = 0),
         native_citizen_hispanic = round(native_citizen_hispanic * allocation_factor, digits = 0),
         total_foreign_non_hispanic = round(total_foreign_non_hispanic * allocation_factor, digits = 0),
         total_foreign_hispanic = round(total_foreign_hispanic * allocation_factor, digits = 0),
         naturalized_citizen_non_hispanic = round(naturalized_citizen_non_hispanic * allocation_factor, digits = 0),
         naturalized_citizen_hispanic = round(naturalized_citizen_hispanic * allocation_factor, digits = 0),
         non_citizen_non_hispanic = round(non_citizen_non_hispanic * allocation_factor, digits = 0),
         non_citizen_hispanic = round(non_citizen_hispanic * allocation_factor, digits = 0),
         native_citizen = native_citizen_non_hispanic + native_citizen_hispanic,
         total_foreign = total_foreign_non_hispanic + total_foreign_hispanic,
         naturalized_citizen = naturalized_citizen_non_hispanic + naturalized_citizen_hispanic,
         non_citizen = non_citizen_non_hispanic + non_citizen_hispanic) %>% 
  select(1,
         state = state.y,
         3,
         puma = puma.x,
         32:33,
         35:40,
         5:17)
```

```{r crosswalk the employment data from PUMAs and ind-occ pairs to counties and ind-occ pairs}
# Join the employment data to the crosswalk data frame
ipums_food_production_by_puma_ind_occ_crosswalked_to_county <- ipums_food_production_by_puma_ind_occ %>% 
  left_join(crosswalk, by = "puma_code") %>% 
  mutate(total_employment_selected_industries = round(total_employment_selected_industries * allocation_factor, digits = 0),
         native_citizen_non_hispanic = round(native_citizen_non_hispanic * allocation_factor, digits = 0),
         native_citizen_hispanic = round(native_citizen_hispanic * allocation_factor, digits = 0),
         total_foreign_non_hispanic = round(total_foreign_non_hispanic * allocation_factor, digits = 0),
         total_foreign_hispanic = round(total_foreign_hispanic * allocation_factor, digits = 0),
         naturalized_citizen_non_hispanic = round(naturalized_citizen_non_hispanic * allocation_factor, digits = 0),
         naturalized_citizen_hispanic = round(naturalized_citizen_hispanic * allocation_factor, digits = 0),
         non_citizen_non_hispanic = round(non_citizen_non_hispanic * allocation_factor, digits = 0),
         non_citizen_hispanic = round(non_citizen_hispanic * allocation_factor, digits = 0),
         native_citizen = native_citizen_non_hispanic + native_citizen_hispanic,
         total_foreign = total_foreign_non_hispanic + total_foreign_hispanic,
         naturalized_citizen = naturalized_citizen_non_hispanic + naturalized_citizen_hispanic,
         non_citizen = non_citizen_non_hispanic + non_citizen_hispanic) %>% 
  select(1,
         state = state.y,
         3,
         puma = puma.x,
         36:37,
         5:8,
         39:44,
         9:21)
```

```{r group the data by county}
# This step is required to deal with situations where multiple PUMAs split a single county
ipums_food_production_by_county <- ipums_food_production_by_puma_crosswalked_to_county %>% 
  group_by(state_code, state, county_code, county) %>% 
  summarize(total_employment_selected_industries = sum(total_employment_selected_industries),
            native_citizen = sum(native_citizen),
            native_citizen_non_hispanic = sum(native_citizen_non_hispanic),
            native_citizen_hispanic = sum(native_citizen_hispanic),
            total_foreign = sum(total_foreign),
            total_foreign_non_hispanic = sum(total_foreign_non_hispanic),
            total_foreign_hispanic = sum(total_foreign_hispanic),
            naturalized_citizen = sum(naturalized_citizen),
            naturalized_citizen_non_hispanic = sum(naturalized_citizen_non_hispanic),
            naturalized_citizen_hispanic = sum(naturalized_citizen_hispanic),
            non_citizen = sum(non_citizen),
            non_citizen_non_hispanic = sum(non_citizen_non_hispanic),
            non_citizen_hispanic = sum(non_citizen_hispanic),
            pct_native_citizen = round(native_citizen / total_employment_selected_industries * 100, digits = 0),
            pct_native_citizen_non_hispanic = round(native_citizen_non_hispanic / total_employment_selected_industries * 100, digits = 0),
            pct_native_citizen_hispanic = round(native_citizen_hispanic / total_employment_selected_industries * 100, digits = 0),
            pct_total_foreign = round(total_foreign / total_employment_selected_industries * 100, digits = 0),
            pct_total_foreign_non_hispanic = round(total_foreign_non_hispanic / total_employment_selected_industries * 100, digits = 0),
            pct_total_foreign_hispanic = round(total_foreign_hispanic / total_employment_selected_industries * 100, digits = 0),
            pct_naturalized_citizen = round(naturalized_citizen / total_employment_selected_industries * 100, digits = 0),
            pct_naturalized_citizen_non_hispanic = round(naturalized_citizen_non_hispanic / total_employment_selected_industries * 100, digits = 0),
            pct_naturalized_citizen_hispanic = round(naturalized_citizen_hispanic / total_employment_selected_industries * 100, digits = 0),
            pct_non_citizen = round(non_citizen / total_employment_selected_industries * 100, digits = 0),
            pct_non_citizen_non_hispanic = round(non_citizen_non_hispanic / total_employment_selected_industries * 100, digits = 0),
            pct_non_citizen_hispanic = round(non_citizen_hispanic / total_employment_selected_industries * 100, digits = 0))

# Export the data
write_csv(ipums_food_production_by_county,
          "data/exported/ipums_food_production_by_county.csv")
```

```{r group the data by industry and occupation and county}
# This step is required to deal with situations where multiple PUMAs split a single county
ipums_food_production_by_county_ind_occ <- ipums_food_production_by_puma_ind_occ_crosswalked_to_county %>% 
  group_by(state_code, state, county_code, county, industry_code, industry, occupation_code, occupation) %>% 
  summarize(total_employment_selected_industries = sum(total_employment_selected_industries),
            native_citizen = sum(native_citizen),
            native_citizen_non_hispanic = sum(native_citizen_non_hispanic),
            native_citizen_hispanic = sum(native_citizen_hispanic),
            total_foreign = sum(total_foreign),
            total_foreign_non_hispanic = sum(total_foreign_non_hispanic),
            total_foreign_hispanic = sum(total_foreign_hispanic),
            naturalized_citizen = sum(naturalized_citizen),
            naturalized_citizen_non_hispanic = sum(naturalized_citizen_non_hispanic),
            naturalized_citizen_hispanic = sum(naturalized_citizen_hispanic),
            non_citizen = sum(non_citizen),
            non_citizen_non_hispanic = sum(non_citizen_non_hispanic),
            non_citizen_hispanic = sum(non_citizen_hispanic),
            pct_native_citizen = round(native_citizen / total_employment_selected_industries * 100, digits = 0),
            pct_native_citizen_non_hispanic = round(native_citizen_non_hispanic / total_employment_selected_industries * 100, digits = 0),
            pct_native_citizen_hispanic = round(native_citizen_hispanic / total_employment_selected_industries * 100, digits = 0),
            pct_total_foreign = round(total_foreign / total_employment_selected_industries * 100, digits = 0),
            pct_total_foreign_non_hispanic = round(total_foreign_non_hispanic / total_employment_selected_industries * 100, digits = 0),
            pct_total_foreign_hispanic = round(total_foreign_hispanic / total_employment_selected_industries * 100, digits = 0),
            pct_naturalized_citizen = round(naturalized_citizen / total_employment_selected_industries * 100, digits = 0),
            pct_naturalized_citizen_non_hispanic = round(naturalized_citizen_non_hispanic / total_employment_selected_industries * 100, digits = 0),
            pct_naturalized_citizen_hispanic = round(naturalized_citizen_hispanic / total_employment_selected_industries * 100, digits = 0),
            pct_non_citizen = round(non_citizen / total_employment_selected_industries * 100, digits = 0),
            pct_non_citizen_non_hispanic = round(non_citizen_non_hispanic / total_employment_selected_industries * 100, digits = 0),
            pct_non_citizen_hispanic = round(non_citizen_hispanic / total_employment_selected_industries * 100, digits = 0))

# Export the data
write_csv(ipums_food_production_by_county_ind_occ,
          "data/exported/ipums_food_production_by_county_ind_occ.csv")
```

### Analyze the data

```{r analyze employment by total foreign}
# What is the total number of workers employed in these industries?
sum(ipums_food_production_by_puma$total_employment_selected_industries)

# What is the total number of foreigners employed in these industries?
sum(ipums_food_production_by_puma$total_foreign)

# What's that as a percent?
sum(ipums_food_production_by_puma$total_foreign) / sum(ipums_food_production_by_puma$total_employment_selected_industries) * 100

# What is the national average of foreign employment?
ipums %>% 
  filter(citizenship_code == "2" | citizenship_code == "3") %>% 
  summarize(sum(PERWT)) /
ipums %>% 
  summarize(sum(PERWT))

# How many of the jobs have a higher proportion of foreigners employed than the national average of 17.1%?
ipums_food_production_by_industry_occupation %>% 
  filter(pct_total_foreign > 17.1) %>% 
  select(industry, occupation, total_employment, pct_total_foreign, pct_total_foreign_hispanic) %>% 
  arrange(desc(total_employment))
```

```{r analyze employment by non-citizen}
# What is the total number of non-citizens employed in these industries?
sum(ipums_food_production_by_puma$non_citizen)

# What's that as a percent?
sum(ipums_food_production_by_puma$non_citizen) / sum(ipums_food_production_by_puma$total_employment_selected_industries) * 100

# What is the national average of non-citizen employment?
ipums %>% 
  filter(citizenship_code == "3") %>% 
  summarize(sum(PERWT)) /
ipums %>% 
  summarize(sum(PERWT))

# How many of the jobs have a higher proportion of foreigners employed than the national average of 8.6%?
ipums_food_production_by_industry_occupation %>% 
  filter(pct_non_citizen > 8.6) %>% 
  select(industry, occupation, total_employment, pct_non_citizen, pct_non_citizen_hispanic) %>% 
  arrange(desc(total_employment))
```

```{r analyze employment by total foreign and Hispanic}
# What is the total number of Hispanic foreigners employed in these industries?
sum(ipums_food_production_by_puma$total_foreign_hispanic)

# What's that as a percent of all foreign workers in these industries?
sum(ipums_food_production_by_puma$total_foreign_hispanic) / sum(ipums_food_production_by_puma$total_foreign) * 100
```

```{r analyze employment by non-citizen and Hispanic}
# What is the total number of Hispanic non-citizens employed in these industries?
sum(ipums_food_production_by_puma$non_citizen_hispanic)

# What's that as a percent of all non-citizen workers in these industries?
sum(ipums_food_production_by_puma$non_citizen_hispanic) / sum(ipums_food_production_by_puma$non_citizen) * 100
```

```{r analyze employment by puma}
# Which PUMAs have the highest number of immigrant foodworkers?
ipums_food_production_by_puma %>% 
  arrange(desc(total_foreign)) %>% 
  select(state, puma, total_employment_selected_industries, total_foreign, total_foreign_hispanic) %>% 
  head(23) # 2,341 PUMAs / 100 = 23.41

# And how many immigrant workers are in these PUMAs?
ipums_food_production_by_puma %>% 
  arrange(desc(total_foreign)) %>% 
  select(puma, total_employment_selected_industries, total_foreign, total_foreign_hispanic) %>% 
  head(23) %>% 
  ungroup() %>% 
  summarize(sum(total_foreign))

# And how many of these foreign-born workers are Hispanic?
ipums_food_production_by_puma %>% 
  arrange(desc(total_foreign)) %>% 
  select(puma, total_employment_selected_industries, total_foreign, total_foreign_hispanic) %>% 
  head(23) %>% 
  ungroup() %>% 
  summarize(sum(total_foreign_hispanic))
```

```{r analyze employment by county}
# Which counties have the highest number of immigrant foodworkers?
ipums_food_production_by_county %>% 
  arrange(desc(total_foreign)) %>% 
  select(state, county, total_employment_selected_industries, total_foreign, total_foreign_hispanic) %>% 
  head(31) # 3,142 counties / 100 = 31.42

# And how many immigrant workers are in these counties?
ipums_food_production_by_county %>% 
  arrange(desc(total_foreign)) %>% 
  select(county, total_employment_selected_industries, total_foreign, total_foreign_hispanic) %>% 
  head(31) %>% 
  ungroup() %>% 
  summarize(sum(total_foreign))

# And how many of these foreign-born workers are Hispanic?
ipums_food_production_by_county %>% 
  arrange(desc(total_foreign)) %>% 
  select(county, total_employment_selected_industries, total_foreign, total_foreign_hispanic) %>% 
  head(31) %>% 
  ungroup() %>% 
  summarize(sum(total_foreign_hispanic))
```

```{r analysis employment and COVID status by state}
# What is the distribution of foreign workers in these industries by state?
foodworkers_by_state <- ipums_food_production_by_puma %>% 
  group_by(state) %>% 
  summarize(state_total_employment_selected_industries = sum(total_employment_selected_industries),
            state_total_foreign = sum(total_foreign),
            state_pct_total_foreign = round(sum(total_foreign) / sum(total_employment_selected_industries) * 100), 2,
            state_total_foreign_hispanic = sum(total_foreign_hispanic),
            state_pct_total_foreign_hispanic = round(sum(total_foreign_hispanic) / sum(total_employment_selected_industries) * 100), 2) %>% 
  mutate(rank_total_employment = dense_rank(desc(state_total_employment_selected_industries)),
         rank_total_foreign = dense_rank(desc(state_total_foreign)),
         rank_total_foreign_hispanic = dense_rank(desc(state_total_foreign_hispanic))) %>% 
  select(state, state_total_employment_selected_industries, state_total_foreign, state_pct_total_foreign, state_total_foreign_hispanic, state_pct_total_foreign_hispanic,
         rank_total_employment,
         rank_total_foreign,
         rank_total_foreign_hispanic) %>% 
  arrange(desc(state_total_employment_selected_industries))

foodworkers_by_state

# What proportion of total foodworker employment do the top 10 states account for?
foodworkers_by_state %>% 
  arrange(desc(state_total_employment_selected_industries)) %>% 
  head(10) %>% 
  summarize(sum(state_total_employment_selected_industries))

  foodworkers_by_state %>% 
  summarize(sum(state_total_employment_selected_industries))
  
# Where do the "Red Zone" states stand?
red_zone <- data.frame("state" = c("Alabama/AL", "Arizona/AZ", "Arkansas/AR", "California/CA", "Florida/FL", "Georgia/GA", "Idaho/ID", "Iowa/IA", "Kansas/KS", "Louisiana/LA", "Mississippi/MS", "Missouri/MO", "Nevada/NV", "North Carolina/NC", "North Dakota/ND", "Oklahoma/OK", "South Carolina/SC", "Tennessee/TN", "Texas/TX", "Utah/UT", "Wisconsin/WI"),
                       "red_zone" = TRUE)

# Join with the red zone states data frame
foodworkers_by_state <- foodworkers_by_state %>% 
  left_join(red_zone, by = "state")

# Where do the Red Zone states stand?
foodworkers_by_state %>% 
  filter(red_zone == TRUE)
  
# Export the states
write_csv(foodworkers_by_state, "data/exported/foodworkers_by_state.csv")
```

---OLD CODE BELOW. IGNORE FOR NOW.---

```{r # visualize the relationship between these industries' employment and cases-per-100k}
# Total industry employment
jpeg("total_employment_covid_cases.jpg", width = 500, height = 500)
attach(ipums_food_production_by_county)
plot(total_employment_selected_industries, cases_per_100k, main = "Total employment in selected food production industries vs. COVID-19 cases per 100,000 population",
     xlab="Total employment in selected food production industries", ylab="COVID-19 cases per 100,000 population", pch=19)
abline(lm(cases_per_100k ~ total_employment_selected_industries), col = "red") # regression line (y~x)
dev.off()

# Non-citizen
jpeg("non_citizen_covid_cases.jpg", width = 500, height = 500)
attach(ipums_food_production_by_county)
plot(non_citizen_non_hispanic + non_citizen_hispanic, cases_per_100k, main = "Non-citizen employment in selected food production industries vs. COVID-19 cases per 100,000 population",
     xlab="Non-citizen employment in selected food production industries", ylab="COVID-19 cases per 100,000 population", pch=19)
abline(lm(cases_per_100k ~ non_citizen_hispanic + non_citizen_hispanic), col = "red") # regression line (y~x)
dev.off()

# Non-citizen, Hispanic
jpeg("non_citizen_hispanic_covid_cases.jpg", width = 500, height = 500)
attach(ipums_food_production_by_county)
plot(non_citizen_hispanic, cases_per_100k, main = "Non-citizen, Hispanic employment in selected food production industries vs. COVID-19 cases per 100,000 population",
     xlab="Non-citizen, Hispanic employment in selected food production industries", ylab="COVID-19 cases per 100,000 population", pch=19)
abline(lm(cases_per_100k ~ non_citizen_hispanic), col = "red") # regression line (y~x)
dev.off()

# Percent non-citizen, Hispanic
jpeg("pct_non_citizen_hispanic_covid_cases.jpg", width = 500, height = 500)
attach(ipums_food_production_by_county)
plot(pct_non_citizen_hispanic, cases_per_100k, main = "Percent non-citizen, Hispanic employment in selected food production industries vs. COVID-19 cases per 100,000 population",
     xlab="Percent non-citizen, Hispanic employment in selected food production industries", ylab="COVID-19 cases per 100,000 population", pch=19)
abline(lm(cases_per_100k ~ pct_non_citizen_hispanic), col = "red") # regression line (y~x)
dev.off()
```
```{r export the data}
write_csv(ipums_food_production_by_puma, "data/exported/ipums_food_production_by_puma.csv")
write_csv(ipums_food_production_by_county, "data/exported/ipums_food_production_by_county.csv")
```

### OLD CODE BELOW:::IGNORE FOR NOW

```{r}
# Join the county-level employment data to the covid and population data
crosswalk <- list(covid, population, crosswalk) %>% 
  reduce(full_join, by = "county_code") %>% 
  mutate(puma = paste(puma, state.x, sep = ", "),
         cases_per_100k = round(cases / population * 100000, digits = 0),
         deaths_per_100k = round(deaths / population * 100000, digits = 0)) %>% 
  select(1,
         state = state.x,
         county_code,
         county = county.y,
         puma_code,
         puma,
         population,
         cases,
         deaths,
         cases_per_100k,
         deaths_per_100k,
         allocation_factor)
```

```{r crosswalk the employment data from PUMAs to counties}
# Join the employment data to the crosswalk data frame
ipums_food_production_by_county <- ipums_food_production_by_puma %>% 
  left_join(crosswalk, by = "puma_code") %>% 
  mutate(total_employees = total_employees * allocation_factor,
            native_citizen = native_citizen * allocation_factor,
            total_foreign = total_foreign * allocation_factor,
            naturalized_citizen = naturalized_citizen * allocation_factor,
            non_citizen = non_citizen * allocation_factor,
            pct_native_citizen = native_citizen / total_employees * 100,
            pct_total_foreign = total_foreign / total_employees * 100,
            pct_naturalized_citizen = naturalized_citizen / total_employees * 100,
            pct_non_citizen = non_citizen / total_employees * 100,
                                    native_citizen_non_hispanic = native_citizen_non_hispanic * allocation_factor,
                                    native_citizen_hispanic = native_citizen_hispanic * allocation_factor,
                                    total_foreign_non_hispanic = total_foreign_non_hispanic * allocation_factor,
                                    total_foreign_hispanic = total_foreign_hispanic * allocation_factor,
                                    naturalized_citizen_non_hispanic = naturalized_citizen_non_hispanic * allocation_factor,
                                    naturalized_citizen_hispanic = naturalized_citizen_hispanic * allocation_factor,
                                    non_citizen_non_hispanic = non_citizen_non_hispanic * allocation_factor,
                                    non_citizen_hispanic = non_citizen_hispanic * allocation_factor,
                                    pct_native_citizen_non_hispanic = native_citizen_non_hispanic / total_employees * 100,
                                    pct_native_citizen_hispanic = native_citizen_hispanic / total_employees * 100,
                                    pct_total_foreign_non_hispanic = total_foreign_non_hispanic / total_employees * 100,
                                    pct_total_foreign_hispanic = total_foreign_hispanic / total_employees * 100,
                                    pct_naturalized_citizen_non_hispanic = naturalized_citizen_non_hispanic / total_employees * 100,
                                    pct_naturalized_citizen_hispanic = naturalized_citizen_hispanic / total_employees * 100,
                                    pct_non_citizen_non_hispanic = non_citizen_non_hispanic / total_employees * 100,
                                    pct_non_citizen_hispanic = non_citizen_hispanic / total_employees * 100)
```

```{r Group the data by county}
# Group the data only by county
citizenship_ethnicity_by_county_grouped <- citizenship_ethnicity_by_county %>% 
  group_by(county_code) %>% 
  summarize(total_employees = sum(total_employees),
            native_citizen = sum(native_citizen),
            total_foreign = sum(total_foreign),
            naturalized_citizen = sum(naturalized_citizen),
            non_citizen = sum(non_citizen),
            pct_native_citizen = round(native_citizen / total_employees * 100, digits = 0),
            pct_total_foreign = round(total_foreign / total_employees * 100, digits = 0),
            pct_naturalized_citizen = round(naturalized_citizen / total_employees * 100, digits = 0),
            pct_non_citizen = round(non_citizen / total_employees * 100, digits = 0),
                                    native_citizen_non_hispanic = sum(native_citizen_non_hispanic),
                                    native_citizen_hispanic = sum(native_citizen_hispanic),
                                    total_foreign_non_hispanic = sum(total_foreign_non_hispanic),
                                    total_foreign_hispanic = sum(total_foreign_hispanic),
                                    naturalized_citizen_non_hispanic = sum(naturalized_citizen_non_hispanic),
                                    naturalized_citizen_hispanic = sum(naturalized_citizen_hispanic),
                                    non_citizen_non_hispanic = sum(non_citizen_non_hispanic),
                                    non_citizen_hispanic = sum(non_citizen_hispanic),
                                    pct_native_citizen_non_hispanic = round(native_citizen_non_hispanic / total_employees * 100, digits = 0),
                                    pct_native_citizen_hispanic = round(native_citizen_hispanic / total_employees * 100, digits = 0),
                                    pct_total_foreign_non_hispanic = round(total_foreign_non_hispanic / total_employees * 100, digits = 0),
                                    pct_total_foreign_hispanic = round(total_foreign_hispanic / total_employees * 100, digits = 0),
                                    pct_naturalized_citizen_non_hispanic = round(naturalized_citizen_non_hispanic / total_employees * 100, digits = 0),
                                    pct_naturalized_citizen_hispanic = round(naturalized_citizen_hispanic / total_employees * 100, digits = 0),
                                    pct_non_citizen_non_hispanic = round(non_citizen_non_hispanic / total_employees * 100, digits = 0),
                                    pct_non_citizen_hispanic = round(non_citizen_hispanic / total_employees * 100, digits = 0)) %>% 
  left_join(crosswalk, by = "county_code")

citizenship_ethnicity_by_county_grouped %>% 
  group_by(county) %>% 
  summarize(count = n()) %>% 
  arrange(desc(count))


# So how many employees do we have in total for all industries, food production industries and high-immigrant food production industry-occupation pairs?
ipums %>% 
  summarize(sum(PERWT))

ipums_food_production %>% 
  summarize(sum(PERWT))

citizenship_ethnicity_by_puma %>% 
  summarize(sum(total_employees))

citizenship_ethnicity_by_county %>% 
  summarize(sum(total_employees))

citizenship_ethnicity_by_county %>% 
  group_by(county) %>% 
  summarize(count = n()) %>% 
  arrange(desc(count))

View(citizenship_ethnicity_by_county %>% 
       filter(county == "Los Angeles County, California"))
```

```{r analyze the data by county}
# What is the total number of workers employed in these industries?
sum(citizenship_ethnicity_by_puma$total_employees)

# What is the total number of foreigners employed in these industries?
sum(citizenship_ethnicity_by_ind_occ_puma$total_foreign)

# What is the total number of Hispanic foreigners employed in these industries?
sum(citizenship_ethnicity_by_ind_occ_puma$total_foreign_hispanic)

# Which PUMAs have the highest number of immigrant foodworkers?
citizenship_ethnicity_by_puma %>% 
  arrange(desc(total_foreign)) %>% 
  select(state, puma, total_employees, total_foreign, total_foreign_hispanic) %>% 
  head(23) # 2,294 PUMAs / 100 = 22.94

# And how many immigrant workers are in these PUMAs?
citizenship_ethnicity_by_puma %>% 
  arrange(desc(total_foreign)) %>% 
  select(puma, total_employees, total_foreign, total_foreign_hispanic) %>% 
  head(23) %>% 
  ungroup() %>% 
  summarize(sum(total_foreign)) # 2,294 PUMAs / 100 = 22.94

# And how many of these foreign-born workers are Hispanic?
citizenship_ethnicity_by_puma %>% 
  arrange(desc(total_foreign)) %>% 
  select(puma, total_employees, total_foreign, total_foreign_hispanic) %>% 
  head(23) %>% 
  ungroup() %>% 
  summarize(sum(total_foreign_hispanic)) # 2,294 PUMAs / 100 = 22.94

# What is the distribution of foreign workers in these industries by state?
foreign_foodworkers_by_state <- citizenship_ethnicity_by_puma %>% 
  group_by(state) %>% 
  summarize(state_total_employees = sum(total_employees),
            state_total_foreign = sum(total_foreign),
            state_pct_total_foreign = round(sum(total_foreign) / sum(total_employees) * 100), 2,
            state_total_foreign_hispanic = sum(total_foreign_hispanic),
            state_pct_total_foreign_hispanic = round(sum(total_foreign_hispanic) / sum(total_employees) * 100), 2) %>% 
  select(state, state_total_employees, state_total_foreign, state_pct_total_foreign, state_total_foreign_hispanic, state_pct_total_foreign_hispanic) %>% 
  arrange(desc(state_pct_total_foreign))
```

```{r analyze the data by PUMA}
# What is the total number of workers employed in these industries?
sum(citizenship_ethnicity_by_ind_occ_puma$total_employees)

# What is the total number of foreigners employed in these industries?
sum(citizenship_ethnicity_by_ind_occ_puma$total_foreign)

# What is the total number of Hispanic foreigners employed in these industries?
sum(citizenship_ethnicity_by_ind_occ_puma$total_foreign_hispanic)

# Which PUMAs have the highest number of immigrant foodworkers?
citizenship_ethnicity_by_puma %>% 
  arrange(desc(total_foreign)) %>% 
  select(state, puma, total_employees, total_foreign, total_foreign_hispanic) %>% 
  head(23) # 2,294 PUMAs / 100 = 22.94

# And how many immigrant workers are in these PUMAs?
citizenship_ethnicity_by_puma %>% 
  arrange(desc(total_foreign)) %>% 
  select(puma, total_employees, total_foreign, total_foreign_hispanic) %>% 
  head(23) %>% 
  ungroup() %>% 
  summarize(sum(total_foreign)) # 2,294 PUMAs / 100 = 22.94

# And how many of these foreign-born workers are Hispanic?
citizenship_ethnicity_by_puma %>% 
  arrange(desc(total_foreign)) %>% 
  select(puma, total_employees, total_foreign, total_foreign_hispanic) %>% 
  head(23) %>% 
  ungroup() %>% 
  summarize(sum(total_foreign_hispanic)) # 2,294 PUMAs / 100 = 22.94

# What is the distribution of foreign workers in these industries by state?
foreign_foodworkers_by_state <- citizenship_ethnicity_by_puma %>% 
  group_by(state) %>% 
  summarize(state_total_employees = sum(total_employees),
            state_total_foreign = sum(total_foreign),
            state_pct_total_foreign = round(sum(total_foreign) / sum(total_employees) * 100), 2,
            state_total_foreign_hispanic = sum(total_foreign_hispanic),
            state_pct_total_foreign_hispanic = round(sum(total_foreign_hispanic) / sum(total_employees) * 100), 2) %>% 
  select(state, state_total_employees, state_total_foreign, state_pct_total_foreign, state_total_foreign_hispanic, state_pct_total_foreign_hispanic) %>% 
  arrange(desc(state_pct_total_foreign))
```

```{r}
write_csv(citizenship_by_ind_occ_puma %>% 
           group_by(industry, industry_code, occupation, occupation_code) %>% 
           distinct(industry, occupation, .keep_all = T) %>% 
           select(industry, industry_code, occupation, occupation_code),
         "data/exported/industry_occupation_pairs.csv")
```

```{r export the data}
# Export the data
st_write(foreign_foodworkers_by_state, "data/exported/foreign_foodworkers_by_state.csv")
st_write(citizenship_ethnicity_by_puma, "data/exported/citizenship_ethnicity_by_puma.geojson", driver = "GeoJSON")
st_write(citizenship_ethnicity_by_ind_occ_puma, "data/exported/citizenship_ethnicity_by_ind_occ_puma.geojson", driver = "GeoJSON")
st_write(citizenship_ethnicity_by_puma, "data/exported/citizenship_ethnicity_by_puma.csv")
st_write(citizenship_ethnicity_by_ind_occ_puma, "data/exported/citizenship_ethnicity_by_ind_occ_puma.csv")
```